In [ ]:
from sklearn.preprocessing import MinMaxScaler
import pandas as pd

In [69]:
df = pd.read_csv('Titanic.csv')

In [70]:
x = df.drop('Survived', axis=1)
y = df['Survived']

In [71]:
x

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [72]:
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 891, dtype: int64

In [73]:
type(x)

num_col = ['Age' , 'Fare']

In [74]:
scaler = MinMaxScaler()
scaler.fit(x[num_col])
x[num_col] = scaler.transform(x[num_col])
x

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,3,"Braund, Mr. Owen Harris",male,0.271174,1,0,A/5 21171,0.014151,NaN,S
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,0.472229,1,0,PC 17599,0.139136,C85,C
2,3,3,"Heikkinen, Miss. Laina",female,0.321438,0,0,STON/O2. 3101282,0.015469,NaN,S
3,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,0.434531,1,0,113803,0.103644,C123,S
4,5,3,"Allen, Mr. William Henry",male,0.434531,0,0,373450,0.015713,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,2,"Montvila, Rev. Juozas",male,0.334004,0,0,211536,0.025374,NaN,S
887,888,1,"Graham, Miss. Margaret Edith",female,0.233476,0,0,112053,0.058556,B42,S
888,889,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,0.045771,NaN,S
889,890,1,"Behr, Mr. Karl Howell",male,0.321438,0,0,111369,0.058556,C148,C
890,891,3,"Dooley, Mr. Patrick",male,0.396833,0,0,370376,0.015127,NaN,Q

## The fit , trasnform , and fit-trasnform
### fit : used to get min and max
### trasnform : used to normalize and scale values
### fit-trasnform :  used to do both in once


### in predection we use only transform 

### we use the transofrm after data spliting to prevenet the data lekage

In [76]:

from category_encoders import OneHotEncoder

In [77]:
Str_cols = ['Sex','Embarked']

In [83]:
encoder = OneHotEncoder(cols=Str_cols , drop_invariant=True)
x = encoder.fit_transform(x)

ValueError: X does not contain the columns listed in cols

In [84]:
x

,PassengerId,Pclass,Name,Sex_1,Sex_2,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked_1,Embarked_2,Embarked_3,Embarked_4
0,1,3,"Braund, Mr. Owen Harris",1,0,0.271174,1,0,A/5 21171,0.014151,NaN,1,0,0,0
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,1,0.472229,1,0,PC 17599,0.139136,C85,0,1,0,0
2,3,3,"Heikkinen, Miss. Laina",0,1,0.321438,0,0,STON/O2. 3101282,0.015469,NaN,1,0,0,0
3,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,1,0.434531,1,0,113803,0.103644,C123,1,0,0,0
4,5,3,"Allen, Mr. William Henry",1,0,0.434531,0,0,373450,0.015713,NaN,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,2,"Montvila, Rev. Juozas",1,0,0.334004,0,0,211536,0.025374,NaN,1,0,0,0
887,888,1,"Graham, Miss. Margaret Edith",0,1,0.233476,0,0,112053,0.058556,B42,1,0,0,0
888,889,3,"Johnston, Miss. Catherine Helen ""Carrie""",0,1,NaN,1,2,W./C. 6607,0.045771,NaN,1,0,0,0
889,890,1,"Behr, Mr. Karl Howell",1,0,0.321438,0,0,111369,0.058556,C148,0,1,0,0
890,891,3,"Dooley, Mr. Patrick",1,0,0.396833,0,0,370376,0.015127,NaN,0,0,1,0